import { useEffect, useMemo, useRef, useState } from 'react'
import { ConditionalReplaceConflictError, type CollectionRef, type SafeS3Client } from '@sparcd/s3-safe'

export type CollectionAssignment = { values: unknown[]; etag: string | null }
export type CollectionRecord = CollectionRef & { etag: string; document: Record<string, unknown>; speciesAssignment: CollectionAssignment; locationsAssignment: CollectionAssignment }
const fields = [['nameProperty', 'Name'], ['organizationProperty', 'Organization'], ['contactInfoProperty', 'Contact'], ['descriptionProperty', 'Description']] as const
const requiredFields = new Set(['nameProperty', 'organizationProperty', 'descriptionProperty'])
const keyOf = (kind: 'species' | 'locations', v: Record<string, unknown>) => String(v[kind === 'species' ? 'scientificName' : 'idProperty'] ?? '').trim().toLocaleLowerCase()
const withoutKey = (kind: 'species' | 'locations', v: Record<string, unknown>) => { const c = { ...v }; delete c[kind === 'species' ? 'scientificName' : 'idProperty']; return c }
const json = (v: unknown) => JSON.stringify(v, null, 2)
export function assignmentDiscrepancies(kind: 'species' | 'locations', assigned: unknown[], registry: unknown[]) { const truth = new Map(registry.map((e) => [keyOf(kind, e as Record<string, unknown>), e as Record<string, unknown>])); return assigned.flatMap((e, index) => { const current = e as Record<string, unknown>; const found = truth.get(keyOf(kind, current)); return !found || JSON.stringify(withoutKey(kind, current)) === JSON.stringify(withoutKey(kind, found)) ? [] : [{ index, current, truth: found }] }) }
export function missingAssignments(kind: 'species' | 'locations', assigned: unknown[], registry: unknown[]) { const keys = new Set(registry.map((e) => keyOf(kind, e as Record<string, unknown>))); return assigned.filter((e) => !keys.has(keyOf(kind, e as Record<string, unknown>))) }
export function assignmentLabel(kind: 'species' | 'locations', e: Record<string, unknown>) { const n = String(e[kind === 'species' ? 'name' : 'nameProperty'] ?? e[kind === 'species' ? 'scientificName' : 'idProperty'] ?? 'Unnamed'); return e.retired === true ? `${n} — Defunct` : n }
export function assignmentHasMinimum(v: unknown[]) { return v.length > 0 }
export function collectionValidationError(c: Record<string, unknown>) { const m = fields.find(([k]) => requiredFields.has(k) && String(c[k] ?? '').trim() === ''); return m ? `${m[1]} is required.` : null }
export function collectionHasChanges(a: Record<string, unknown>, b: Record<string, unknown>) { return JSON.stringify(a) !== JSON.stringify(b) }

export function CollectionEditor({ collections, client, actor, reload, speciesRegistry, locationsRegistry }: { collections: CollectionRecord[]; client: SafeS3Client; actor: string; reload: () => void; speciesRegistry: unknown[]; locationsRegistry: unknown[] }) {
  const first = collections[0]; const [selectedKey, setSelectedKey] = useState(first?.key ?? ''); const [draft, setDraft] = useState(first?.document ?? {})
  const [assignments, setAssignments] = useState({ species: first?.speciesAssignment.values ?? [], locations: first?.locationsAssignment.values ?? [] }); const [etags, setEtags] = useState({ species: first?.speciesAssignment.etag ?? null, locations: first?.locationsAssignment.etag ?? null })
  const [open, setOpen] = useState({ species: false, locations: false }); const [search, setSearch] = useState({ species: '', locations: '' }); const [message, setMessage] = useState(''); const [dialog, setDialog] = useState(false); const [undo, setUndo] = useState<{ species: unknown[] | null; locations: unknown[] | null }>({ species: null, locations: null }); const dialogRef = useRef<HTMLDialogElement>(null)
  const [collectionSearch, setCollectionSearch] = useState<string | null>(null); const selected = useMemo(() => collections.find((c) => c.key === selectedKey) ?? null, [collections, selectedKey]); const discrepancy = useMemo(() => ({ species: assignmentDiscrepancies('species', assignments.species, speciesRegistry), locations: assignmentDiscrepancies('locations', assignments.locations, locationsRegistry) }), [assignments, speciesRegistry, locationsRegistry]); const missing = useMemo(() => ({ species: missingAssignments('species', assignments.species, speciesRegistry), locations: missingAssignments('locations', assignments.locations, locationsRegistry) }), [assignments, speciesRegistry, locationsRegistry])
  useEffect(() => { const next = collections.find((c) => c.key === selectedKey) ?? collections[0]; setSelectedKey(next?.key ?? ''); setDraft(next?.document ?? {}); setAssignments({ species: next?.speciesAssignment.values ?? [], locations: next?.locationsAssignment.values ?? [] }); setEtags({ species: next?.speciesAssignment.etag ?? null, locations: next?.locationsAssignment.etag ?? null }); setOpen({ species: false, locations: false }); setDialog(false); setUndo({ species: null, locations: null }) }, [collections])
  useEffect(() => { if (dialog) { dialogRef.current?.showModal(); dialogRef.current?.querySelector<HTMLElement>('button')?.focus() } else if (dialogRef.current?.open) dialogRef.current.close() }, [dialog])
  if (!selected) return <section className="border border-rule bg-panel p-4"><h1>Collections</h1><p>No collections are visible to these credentials.</p></section>
  const selectCollection = (key: string) => { const n = collections.find((c) => c.key === key); if (!n) return; setSelectedKey(key); setDraft(n.document); setAssignments({ species: n.speciesAssignment.values, locations: n.locationsAssignment.values }); setEtags({ species: n.speciesAssignment.etag, locations: n.locationsAssignment.etag }); setCollectionSearch(null); setOpen({ species: false, locations: false }); setDialog(false); setUndo({ species: null, locations: null }) }
  const mutate = (kind: 'species' | 'locations', next: unknown[]) => { setUndo((u) => ({ ...u, [kind]: assignments[kind] })); setAssignments((a) => ({ ...a, [kind]: next })) }
  const saveAssignments = async (kind: 'species' | 'locations') => { const values = assignments[kind]; const noun = kind === 'species' ? 'species' : 'location'; if (!values.length) { setMessage(`At least one ${noun} assignment is required.`); return } const key = `Collections/${selected.uuid}/${kind}.json`; const id = crypto.randomUUID(); const at = new Date().toISOString(); const base = `Settings/audit/config/${at.slice(0, 10)}/${id}`; const event = { schemaVersion: 1, eventId: id, occurredAt: at, actor, action: `${kind}.assignment.updated`, target: { collectionKey: selected.key, key }, before: selected[`${kind}Assignment`].values, after: values }; try { await client.writeImmutable(selected.bucket, `${base}.prepared.json`, json(event), { contentType: 'application/json' }); let etag: string | undefined; if (etags[kind]) etag = (await client.replaceIfUnchanged(selected.bucket, key, json(values), { etag: etags[kind]!, contentType: 'application/json' })).etag; else await client.writeImmutable(selected.bucket, key, json(values), { contentType: 'application/json' }); await client.writeImmutable(selected.bucket, `${base}.applied.json`, json({ ...event, appliedAt: new Date().toISOString(), afterETag: etag }), { contentType: 'application/json' }); setMessage(`Saved ${kind} assignments and audited.`); reload() } catch (e) { setMessage(e instanceof ConditionalReplaceConflictError ? `The ${kind} assignments changed elsewhere. Reload and review them before saving.` : (e as Error).message) } }
  const saveMetadata = async () => { const invalid = collectionValidationError(draft); if (invalid) { setMessage(invalid); return } const id = crypto.randomUUID(); const at = new Date().toISOString(); const base = `Settings/audit/config/${at.slice(0, 10)}/${id}`; const event = { schemaVersion: 1, eventId: id, occurredAt: at, actor, action: 'collection.updated', target: { collectionKey: selected.key }, before: selected.document, after: draft }; try { await client.writeImmutable(selected.bucket, `${base}.prepared.json`, json(event), { contentType: 'application/json' }); const write = await client.replaceIfUnchanged(selected.bucket, `Collections/${selected.uuid}/collection.json`, json(draft), { etag: selected.etag, contentType: 'application/json' }); await client.writeImmutable(selected.bucket, `${base}.applied.json`, json({ ...event, appliedAt: new Date().toISOString(), afterETag: write.etag }), { contentType: 'application/json' }); setMessage('Saved and audited.'); reload() } catch (e) { setMessage(e instanceof ConditionalReplaceConflictError ? 'The collection changed elsewhere. Reload and review it before saving.' : (e as Error).message) } }
  const update = (kind: 'species' | 'locations', index: number) => mutate(kind, assignments[kind].map((e, i) => i === index ? discrepancy[kind].find((d) => d.index === index)?.truth ?? e : e)); const updateAll = (kind: 'species' | 'locations') => mutate(kind, assignments[kind].map((e, i) => discrepancy[kind].find((d) => d.index === i)?.truth ?? e)); const count = discrepancy.species.length + discrepancy.locations.length + missing.species.length + missing.locations.length
  const notice = discrepancy.species.length && discrepancy.locations.length ? `${discrepancy.species.length} species and ${discrepancy.locations.length} locations differ from the current lists. Review updates in the sections below.` : discrepancy.species.length ? `${discrepancy.species.length} assigned species ${discrepancy.species.length === 1 ? 'differs' : 'differ'} from the current list. Review ${discrepancy.species.length === 1 ? 'it' : 'them'} below.` : discrepancy.locations.length ? `${discrepancy.locations.length} assigned location${discrepancy.locations.length === 1 ? '' : 's'} ${discrepancy.locations.length === 1 ? 'differs' : 'differ'} from the current list. Review ${discrepancy.locations.length === 1 ? 'it' : 'them'} below.` : missing.species.length ? `${missing.species.length} assigned species ${missing.species.length === 1 ? 'is' : 'are'} no longer present in the current list. Review ${missing.species.length === 1 ? 'it' : 'them'} below.` : `${missing.locations.length} assigned location${missing.locations.length === 1 ? '' : 's'} ${missing.locations.length === 1 ? 'is' : 'are'} no longer present in the current list. Review ${missing.locations.length === 1 ? 'it' : 'them'} below.`
  return <section className="border border-rule bg-panel" aria-labelledby="collections-heading"><div className="border-b border-rule px-4 py-3"><h1 id="collections-heading">Collections</h1><p>Update collection metadata without changing its bucket or unique ID (UUID).</p></div><div className="p-4"><label htmlFor="collection-selector">Select collection</label>{count > 0 && <p role="status" className="text-warn">{notice}</p>}<div className="border border-ruleSoft bg-paper px-3 py-2"><span className="block">{selected.name ?? selected.bucket}</span><span className="block font-mono text-xs break-all">{selected.uuid}</span></div><input id="collection-selector" aria-label="Select collection" list="collection-records" value={collectionSearch ?? ''} onChange={(e) => { setCollectionSearch(e.target.value); const n = collections.find((c) => `${c.name ?? c.bucket} — ${c.uuid}` === e.target.value); if (n) selectCollection(n.key) }} onBlur={() => setCollectionSearch(null)} placeholder="Type to filter collections" /><datalist id="collection-records">{collections.map((c) => <option key={c.key} value={`${c.name ?? c.bucket} — ${c.uuid}`} />)}</datalist><fieldset><legend>Edit {selected.name ?? selected.uuid}</legend>{fields.map(([key, label]) => <label key={key}>{label}{requiredFields.has(key) && <span aria-hidden="true">*</span>}<input required={requiredFields.has(key)} aria-label={label} value={String(draft[key] ?? '')} onChange={(e) => setDraft((d) => ({ ...d, [key]: e.target.value }))} /></label>)}</fieldset><button type="button" disabled={!collectionHasChanges(draft, selected.document)} onClick={() => void saveMetadata()}>Save collection</button>
    {(['species', 'locations'] as const).map((kind) => { const noun = kind === 'species' ? 'species' : 'locations'; const registry = kind === 'species' ? speciesRegistry : locationsRegistry; const list = assignments[kind]; const rows = list.map((entry, originalIndex) => ({ entry, originalIndex })).sort((a, b) => assignmentLabel(kind, a.entry as Record<string, unknown>).localeCompare(assignmentLabel(kind, b.entry as Record<string, unknown>))); const hasChanges = JSON.stringify(list) !== JSON.stringify(selected[`${kind}Assignment`].values); return <details key={kind} open={open[kind]} onToggle={(e) => { const value = (e.currentTarget as HTMLDetailsElement).open; setOpen((o) => ({ ...o, [kind]: value })); if (value && (discrepancy[kind].length || missing[kind].length)) setDialog(true) }}><summary>Assigned {noun}</summary><div><label htmlFor={`${kind}-search`}>Add existing {noun}</label><div><input id={`${kind}-search`} list={`${kind}-options`} value={search[kind]} placeholder={`Type to filter ${noun}`} onChange={(e) => setSearch((s) => ({ ...s, [kind]: e.target.value }))} /><button type="button" aria-label={`Clear ${noun} search`} title={`Clear ${noun} search`} onClick={() => setSearch((s) => ({ ...s, [kind]: '' }))}>×</button></div><datalist id={`${kind}-options`}>{registry.filter((e) => assignmentLabel(kind, e as Record<string, unknown>).toLocaleLowerCase().includes(search[kind].toLocaleLowerCase())).map((e, i) => <option key={i} value={assignmentLabel(kind, e as Record<string, unknown>)} />)}</datalist>{search[kind] && registry.some((e) => assignmentLabel(kind, e as Record<string, unknown>).toLocaleLowerCase() === search[kind].toLocaleLowerCase()) && <button type="button" onClick={() => { const e = registry.find((r) => assignmentLabel(kind, r as Record<string, unknown>).toLocaleLowerCase() === search[kind].toLocaleLowerCase()); if (e && !list.some((x) => keyOf(kind, x as Record<string, unknown>) === keyOf(kind, e as Record<string, unknown>))) mutate(kind, [...list, e]); setSearch((s) => ({ ...s, [kind]: '' })) }}>Add</button>}<ul>{rows.map(({ entry, originalIndex }) => <li key={originalIndex}>{assignmentLabel(kind, entry as Record<string, unknown>)}{!registry.some((e) => keyOf(kind, e as Record<string, unknown>) === keyOf(kind, entry as Record<string, unknown>)) && <span> — Missing</span>}<button type="button" onClick={() => mutate(kind, list.filter((_, i) => i !== originalIndex))}>Remove</button></li>)}</ul>{undo[kind] && <button type="button" onClick={() => { setAssignments((a) => ({ ...a, [kind]: undo[kind]! })); setUndo((u) => ({ ...u, [kind]: null })) }}>Undo</button>}<button type="button" disabled={!assignmentHasMinimum(list) || !hasChanges} onClick={() => void saveAssignments(kind)}>Save {noun}</button>{!assignmentHasMinimum(list) && <p role="alert">At least one {kind === 'species' ? 'species' : 'location'} assignment is required.</p>}</div></details> })}
    <dialog ref={dialogRef} onCancel={(e) => { e.preventDefault(); setDialog(false) }} onClick={(e) => { if (e.target === e.currentTarget) setDialog(false) }}><h2>Registry updates available</h2>{(['species', 'locations'] as const).map((kind) => discrepancy[kind].length > 0 && <section key={kind}><h3>{kind === 'species' ? 'Species' : 'Locations'}</h3><button type="button" onClick={() => updateAll(kind)}>Update all</button><ul>{discrepancy[kind].map((d) => <li key={d.index}>{assignmentLabel(kind, d.current)} <button type="button" onClick={() => update(kind, d.index)}>Update</button></li>)}</ul></section>)}<button type="button" onClick={() => setDialog(false)}>Close</button></dialog>{message && <p role="status">{message}</p>}</div></section>
}
