import { StrictMode, useEffect, useState } from 'react'; import { createRoot } from 'react-dom/client';
import { Connection, loadPersistedConnection, loadSessionConnection, saveSharedConnection, subscribeSharedConnection } from '@sparcd/auth-ui';
import type { S3Config } from '@sparcd/types'; import { SafeS3Client, ConditionalReplaceConflictError } from '@sparcd/s3-safe'; import './style.css';
const LOC='Settings/locations.json', SPEC='Settings/species.json'; type Registry={key:string; value:unknown[]; etag:string; bucket:string};
const json=(x:unknown)=>JSON.stringify(x,null,2); const id=()=>crypto.randomUUID();
async function bucket(c:SafeS3Client){for(const b of await c.listBuckets())try{await c.statObject(b,LOC);return b}catch{} throw Error('No readable settings bucket.');}
async function load(cfg:S3Config){const c=new SafeS3Client(cfg,['*'],['*']);const b=await bucket(c);const read=async(key:string):Promise<Registry>=>{const s=await c.statObject(b,key);return {key,value:JSON.parse(new TextDecoder().decode(await c.getObject(b,key))),etag:s.etag!,bucket:b}};return {c,b,species:await read(SPEC),locations:await read(LOC)};}
async function gate(cfg:S3Config){const {c,b}=await load(cfg);await c.writeImmutable(b,`Settings/admin-sessions/${id()}.json`,json({schemaVersion:1,openedAt:new Date().toISOString(),accessKey:cfg.accessKey}),{contentType:'application/json'});}
function App(){const [cfg,setCfg]=useState<S3Config|null>(null),[data,setData]=useState<Awaited<ReturnType<typeof load>>|null>(null),[error,setError]=useState(''); const authorize=async(c:S3Config,remember=true)=>{setError('');try{await gate(c);saveSharedConnection(c,remember);setCfg(c);setData(await load(c));}catch(e){setCfg(null);setData(null);setError(`Admin access was not established: ${(e as Error).message}`)}}; useEffect(()=>{const c=loadSessionConnection();if(c)void authorize(c);return subscribeSharedConnection((v)=>{if(v)void authorize(v);else {setCfg(null);setData(null)}},()=>cfg)},[]); if(!cfg)return <><Connection toolName="Admin" initialConfig={loadPersistedConnection()??undefined} onConnect={(c,r)=>void authorize(c,r)}/>{error&&<p role="alert" className="error">{error}</p>}</>; return <main><h1>SPARC'd · Admin</h1><p>Connected credentials have configuration-write access.</p><RegistryEditor title="Species" registry={data!.species} client={data!.c} reload={()=>void authorize(cfg)} /><RegistryEditor title="Locations" registry={data!.locations} client={data!.c} reload={()=>void authorize(cfg)} /></main>}
function RegistryEditor({title,registry,client,reload}:{title:string;registry:Registry;client:SafeS3Client;reload:()=>void}){const [text,setText]=useState(json(registry.value)),[message,setMessage]=useState(''); const save=async()=>{try{const after=JSON.parse(text);const at=new Date().toISOString();const event={schemaVersion:1,eventId:id(),occurredAt:at,action:`${title.toLowerCase()}.updated`,target:{registryKey:registry.key},before:registry.value,after};await client.replaceIfUnchanged(registry.bucket,registry.key,json(after),{etag:registry.etag,contentType:'application/json'});await client.writeImmutable(registry.bucket,`Settings/audit/config/${at.slice(0,10)}/${event.eventId}.json`,json(event),{contentType:'application/json'});setMessage('Saved and audited.');reload()}catch(e){setMessage(e instanceof ConditionalReplaceConflictError?'The registry changed elsewhere. Reload and review it before saving.':(e as Error).message)}};return <section><h2>{title}</h2><textarea aria-label={`${title} JSON`} value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>void save()}>Save {title}</button><p role="status">{message}</p></section>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
